// Generated by scripts/capture-telkom-fundamentals.mjs from an official issuer PDF.
import type { FundamentalSnapshot } from '../domain/types'

export const tlkmH12026Snapshot: FundamentalSnapshot = {
  "ticker": "TLKM",
  "reportingPeriod": "H1 2026, six months ended 30 June 2026",
  "periodType": "H1",
  "publicationDate": "2026-07-31",
  "retrievedAt": "2026-09-19T08:02:41.250Z",
  "source": "PT Telekomunikasi Indonesia Tbk. and its subsidiaries, Consolidated Financial Statements 2Q 2026, consolidated statements, pp. 1–5",
  "sourceUrl": "https://www.telkom.co.id/minio/show/data/lampiran/1785496444169_original_Telkom-FS-English-TW-II-2026.pdf",
  "sourceQuality": "OFFICIAL_ISSUER",
  "consolidation": "Consolidated",
  "metrics": [
    {
      "key": "totalAssets",
      "name": "Total assets",
      "value": 303087,
      "unit": "IDR billion",
      "status": "REPORTED"
    },
    {
      "key": "totalEquity",
      "name": "Total equity",
      "value": 134848,
      "unit": "IDR billion",
      "status": "REPORTED"
    },
    {
      "key": "revenue",
      "name": "Revenue",
      "value": 75878,
      "unit": "IDR billion",
      "status": "REPORTED"
    },
    {
      "key": "operatingProfit",
      "name": "Operating profit",
      "value": 20133,
      "unit": "IDR billion",
      "status": "REPORTED"
    },
    {
      "key": "netProfit",
      "name": "Profit for the period",
      "value": 14206,
      "unit": "IDR billion",
      "status": "REPORTED"
    },
    {
      "key": "basicEps",
      "name": "Basic earnings per share",
      "value": 107.5,
      "unit": "IDR per share",
      "status": "REPORTED"
    },
    {
      "key": "operatingCashFlow",
      "name": "Net cash provided by operating activities",
      "value": 34862,
      "unit": "IDR billion",
      "status": "REPORTED"
    }
  ]
}
